apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegorov-admission-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: aegorov-admission-webhook
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aegorov-admission-webhook
  template:
    metadata:
      labels:
        app: aegorov-admission-webhook
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: aegorov-admission-webhook
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
      - name: server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--config-file", "/etc/webhook/config.yaml"]
        ports:
        - containerPort: 8443
          name: tls
        - containerPort: 80
          name: metrics
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /etc/webhook/certs/
          readOnly: true
        - name: config-volume
          mountPath: /etc/webhook/
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: aegorov-admission-tls
      - name: config-volume
        configMap:
          name: webhook-config