apiVersion: v1
kind: Service
metadata:
  name: aegorov-admission
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: aegorov-admission-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics