apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aegorov-admission.default.cluster.local
  namespace: default
  labels:
    component: mutating-controller
webhooks:
  - name: aegorov-admission.default.cluster.local
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiakNDQWxhZ0F3SUJBZ0lVZVBpSmVaeTZ1bjBJV3BrRjJ5MkhobDNFb2pRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1R6RUxNQWtHQTFVRUJoTUNVbFV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RHpBTkJnTlZCQWNUQmsxdgpjMk52ZHpFUU1BNEdBMVVFQ2hNSFJYaGhiWEJzWlRFTE1Ba0dBMVVFQ3hNQ1EwRXdIaGNOTWpNd05ERTJNVGt3Ck5UQXdXaGNOTWpnd05ERTBNVGt3TlRBd1dqQlBNUXN3Q1FZRFZRUUdFd0pTVlRFUU1BNEdBMVVFQ0JNSFJYaGgKYlhCc1pURVBNQTBHQTFVRUJ4TUdUVzl6WTI5M01SQXdEZ1lEVlFRS0V3ZEZlR0Z0Y0d4bE1Rc3dDUVlEVlFRTApFd0pEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXk0TnMydmdMVkJDK3BkCmVzUjByZEUvRE1oTU5vbWdsOFVGcWNrRW9aN25RVzRpK0FTMTdjT0lGQlNFS3AvejhpVmFycU1nVWp4bG1haUIKVnNWamdRNHdBclVoWkZOandjVHhibDl5RXBseDlBY3prbVZqeWMvNjBzendueXkxOS9ueEFMMGM1MXNHMnBUUAorR01SMTAwRXkwNzVTM0czZDVxMUJCU1FCeFhyckdLbTBxTjVSb2RGQ0ZDZUFvaFBKQXh4WVRIdThUTktPTHZYCkY5bEZrdHZVMEJndDd4NlBJMGgzR3pma0VrblV3aXMrYmtuaUZPY3p6d3ZtWStVVDRoNlRoSFdUL0dzMFFoWnUKTjVZOWxXSzFnTGdBY3grb0FXdmVDa243bnJ4SktaaFF0T09Kd2JNOFdMSWI4UldDWVBNeWtGbEljV1FabU1FVgpUb1ppWmVNQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3CkhRWURWUjBPQkJZRUZOelFDeG1DWTlpc2RuNjE3N3VLWVllTERrK01NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFDSjkrV0NyNlNVK0FrUzBXVE1mU3ZMTXA0ZXM4NGc5dnArMXZwOGJqVjkvU0FWaHFYVE1LeEl3S09ZZkRvcQpsNzQvaVhROHZxaHdjeSttQlNYRDFLbDhNN1FOK0llemVYWmtDcDZLVCs3MmtOaXFoQTJSSlRDZ204VzhnL3BCCnFRRjA3K2s1clI1TEdsSjhvcHZKT2hJNCt4ZnIzbGdWbjdxV3ZWV2VYQ1A5WERnZDhlVjJYWWlLNnY2aDFZUnEKRnJnN0xaQXdWMlpWV1hwM05IR01nVytLKzBsdHVwVmRZSWxQU3RiOUlIYUpFM1llbk1HelgyY0hiR1ZMaXBkKwowcEV0QmpOdUp2Ny9DVytGNkpQYjZhMVhSa3Jmd1kxSC9rbk8ybS9UMWRCaVV1dmdpWjU1KzMxYjkySllKakh2CmZhT0srMjl3a0NJT3VudXJxQ3UvVUptcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - apiGroups: [ "apps" ]
        resources:
          - "statefulset"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE