general:
  port: 8443
  tlsCertFile: sourcecode/tls.crt
  tlsKeyFile: sourcecode/tls.key
  logLevel: info
triggerLabel:
  notebook-name: "*"
patchData:
  labels:
    type-app: "notebook"
  annotations:
    sidecar.istio.io/componentLogLevel: "wasm:debug"
    sidecar.istio.io/userVolume: "[{\"name\":\"wasmfilters-dir\",\"emptyDir\": { } } ]"
    sidecar.istio.io/userVolumeMount: "[{\"mountPath\":\"/var/local/lib/wasm-filters\",\"name\":\"wasmfilters-dir\"}]"
